"""empty message

Revision ID: ce2b24a5b7fc
Revises: dcc343a46ab1
Create Date: 2024-07-22 19:57:58.645016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce2b24a5b7fc'
down_revision: Union[str, None] = 'dcc343a46ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'User', 'Comment', ['role_id'], ['id'])
    op.drop_column('User', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'is_verified')
    op.drop_column('User', 'is_superuser')
    op.drop_column('User', 'is_active')
    op.drop_column('User', 'role_id')
    # ### end Alembic commands ###
